NREL/openstudio-standards

measures/create_DOE_prototype_building/measure.rb
This enables warehouse as an option for the measure when creating the prototype buildings.
Caveat: The newer vintages align well with the legacy IDFs but the older vintages do not at the time of this pull request.
The Pre-1980 and Post-1980 Warehouse models have very high cooling and fan energy which still need to be investigated further.
=> Enable warehouse

openstudio-standards/lib/openstudio-standards/utilities/simulation.rb
Adding support for the new openstudio-workflow gem, (see https://github.com/NREL/OpenStudio-workflow-gem/tree/osw) based off of the version of the openstudio-workflow required. Currently there is no good way of testing this functionality. @asparke2 @macumber It might be worthwhile to consider how to test this code. Given the need for separate gemfiles the best solution may be to move the below code into the core CLI and rely on the CLI tests.
=> Adding simulation code for the OS 2.0 WFG

openstudio-standards/lib/openstudio-standards.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb
Currently if you a zone that has a need for 10 kTBU/hr and a multiplier or 10, the COP is calculated based on the total load of 100 kBTU/hr and leads to a COP lower than it should be.
=> Fix the PTAC and PTHP setStandardEfficiencyAndCurves to take into account zone Multiplier

openstudio-standards/lib/openstudio-standards/utilities/simulation.rb
2x code is based on what is used for reporting measure tests. Create
OSW and run that with CLI.
@asparke2 test in measure repo runs fine with these updates. I don't have a 1x to test but I shouldn't have changed what happens for 1.x.
=> fixes simulation.rb to work with 2x OS

openstudio-standards/Rakefile, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.swh.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.building_specific_methods.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.full_service_restaurant.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.high_rise_apartment.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.hospital.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.large_hotel.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.large_office.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.medium_office.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.mid_rise_apartment.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.outpatient.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.primary_school.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.quick_service_restaurant.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.retail_standalone.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.retail_stripmall.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.secondary_school.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.small_hotel.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.small_office.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.warehouse.rb, openstudio-standards/test/bin/docker-run-2.sh, openstudio-standards/test/bin/docker-run.sh, openstudio-standards/test/test_find_ashrae_hot_water_demand.rb, openstudio-standards/test/test_find_construction_properties_data.rb, openstudio-standards/test/test_primary_school.rb, openstudio-standards/test/test_small_office.rb
@phylroy With the changes on this branch I fixed the issue where you had to split the NECB tests out separately.  This issue was being caused by was dynamically reloading building-type specific files.  By moving these into separate modules, this problem is avoided.  However, one thing I noticed is making the NECB tests separate was preventing the reporting from happening for the gem_nrel_group_3 tests because they were being overwritten by the NECB test results.  As s result, I put the NECB tests back into the gem_group_3 directly.  Could you check out this build and let me know if this will work for you?
https://circleci.com/gh/NREL/openstudio-standards/611#tests/containers/0
=> Fix method redefining issue 144

openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
Related to: https://unmethours.com/question/22914/openstudio-baseline-building-measure-error/
=> Added clearer error message if AirLoopHVAC serves zero floor area

openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb, openstudio-standards/test/circleci_tests.txt
loads the legacy IDF results from the embedded filesystem rather than disk when called from inside the CLI.  Should only impact the QAQC measure that calls find_target_eui
=> Fix load legacy results in cli

lib/openstudio-standards/standards/necb/necb_2011/necb_2011.rb
Created a new method called "build_prototype_model" which contains most of the code in model_create_prototype_model.  This separates the building the prototype (build_prototype_model) and replacing the initial model with the prototype model.  This was done so that another pump sizing run and some pump code can be added to support NECB 2015 without copying all of model_create_prototype_model in NECB 2015.
=> Split model_create_prototype_model into two methods

.gitignore, .rubocop.yml
@asparke2 -- this should be an easy merge. We are moving the rubocop syntax to S3. No longer needs https to download.
=> update rubocop style location

lib/openstudio-standards/standards/Standards.Model.rb
- account for zone multiplier when calculating zone internal loads
- better log message for model_eliminate_outlier_zones termination
=> account for multiplier with internal loads

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb
Fixes two errors.
1) Variable should be space.name and not name.get.
2) In the `model_eliminate_outlier_zones` method, if the array_of_zones has NaNs in the key_to_inspect, then raised an exception on sort. Cat this exception and simply act on the array_of_zones in the order that was passed. 
Needed for running the gbxml test case here: https://github.com/NREL/openstudio-cli-demo/tree/2.6.0/gbxml_osw
=> Fix invalid variable, catch NaNs when sorting

data/standards/export_OpenStudio_libraries.rb
I modified `export_OpenStudio_libraries.rb` to use [Parallel](https://github.com/grosser/parallel) because it's taking such a long time and each iteration of the for loop is really independent.
```ruby
gem install parallel
bundle exec rake library:export
```
I also caught a few weird things in the script. If it can't find the template in question, it still tries to do it which will fail. And currently there was a line that would basically only make it run for 90.1.2004
=> Parallelize export of OpenStudio libraries

lib/openstudio-standards/standards/necb/NECB2011/qaqc/necb_qaqc.rb, test/necb/test_necb_qaqc_single.rb
This is currently disabled as most tests are now done using regression and unit tests.. but we may bring this back, maybe for NECB checklist reporting.... so the method is commented out.
=> allows btap results to run on 2011-17 vintages

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
While running QC/QC on the tenant star project, @mpraprost encountered several cooling towers operating near or at full-load for some of their run time, which indicates undersized equipment.
The default condenser loop in openstudio-standards uses an 85°F leaving water temperature for cooling tower design sizing and a constant 70°F temperature setpoint schedule at the condenser water supply outlet node.  This means the tower frequently operates at or near full capacity to meet the 70°F target, and operates at full capacity any time the wet bulb is over 70°F.
This pull request replaces the constant 70°F setpoint and instead uses a follow outdoor air temperature controller keyed to outdoor air wet bulb with a 7°F approach and 70°F min and 85°F max.
There is a [method in the prm …
=> change default condenser loop to follow OATwb with 7F approach

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/ashrae_90_1_2013.Space.rb
Deactivate daylighting control for sidelighting for the retail prototypes for 90.1-2010 (exception c to section 9.4.1.4 of 90.1-2010) and 90.1-2013 (exception 3 to section Section 9.4.1.1(e)).
=> Retail space exception to daylighting controls for sidelighting

lib/openstudio-standards/standards/Standards.Model.rb
changes model_add_schedule to return an always on discrete schedule instead of false.  The code still throws an error message.
@asparke2 this needs to be merged into the LA100 branch too
=> model_add_schedule return sch

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
The latest version of OpenStudio supports Exterior:FuelEquipment. The proposed changes use ExteriorFuelEquipment instead of ExteriorLights. This doesn't affect the results but helps when comparing individual end-uses.
=> Use ExteriorFuelEquipment instead of ExteriorLights

lib/openstudio-standards/standards/Standards.WaterHeaterMixed.rb
The off/on cycle parasitic fuel consumption is used to capture pipe heat loss so it cannot be used to heat the tank.
=> Correct Off Cycle Parasitic Heat Fraction to Tank

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
The minimum outdoor airflow rate was never set to be autosized (the default value is 0) for PSZ-AC systems. One of the consequences is that no ERVs were created because, for most standards, the ERV requirement depends on the percentage of outdoor air flow rate to design flow rate which was always 0.
I will create another pull request to add tests to check that ERVs are created when required for a few known cases.
=> [PSZ-AC] Autosizing minmium outdoor airflow rate so ERV can be created when necessary

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.Space.rb
Exception b to Section 9.4.1.4 to 90.1-2010 should be ignored when generating the DOE prototypes. There is no code requirement in 90.1-2010 for visible transmittance hence, the sidelighted effective aperture area for prototypes is not evaluated. The proposed change uses the `@instvarbuilding` variable, that is only defined when creating a prototype, to skip the sidelighted effective aperture exception test. This should not impact the baseline model creation for performance rating methods as the variable isn't defined and as a result `@instvarbuilding_type.nil?` should always be `true`.
=> Ignore Exception b to Section 9.4.1.4 to 90.1-2010

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.CoilDX.rb
The proposed changes include an instance variable that is used to retrieve the heating section type before looking up the cooling coil efficiency.
=> Retrieves the heating section type for PSZ-AC

data/geometry/ASHRAEPrimarySchool.osm, data/geometry/ASHRAESecondarySchool.osm
The `ComputerRoom` space type was missing from some of the schools templates but is already included in the space types json file.
=> Add Computer Rooms to All 90.1 Schools Templates

test/helpers/compare_models_helper.rb
default to a tenth of a percent tolerance rather than exact match to avoid tiny errors in regression models
=> set regression test threshold for numeric field comparisons

lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb
added logic in the standards: if AS heater control set to RelativeHumidity in the spreadsheet, it is set to Linear in the models.
=> As heater control bug fix

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, test/doe_prototype/test_add_hvac_systems.rb
This fix does two things:
1) Sets the zone DOAS air terminal as the 1st priority for zone heating and cooling so that it's effect on the zone air is included
2) Sets the sequential cooling fraction and sequential heating fraction to zero so that the DOAS air terminal is only expected to provide ventilation, not zone conditioning.  In the case of economizing, the sequential cooling fraction is set to 1.0 to enable economizing, and is mutually exclusive of DCV.
=> correct DOAS method to enable DCV

lib/openstudio-standards/standards/Standards.Model.rb
If a user makes a prototype HVAC system, or otherwise uses EMS objects in their model, these may get orphaned when running the prm_baseline method which removes all HVAC and service water heating.
This method removes EMS objects so that the baseline model can be made cleanly.
Intends to fix [NREL/OpenStudio issue #3279](https://github.com/NREL/OpenStudio/issues/3279) and #688.
=> remove ems objects when calling model_create_prm_baseline_building

lib/openstudio-standards/prototypes/common/prototype_metaprogramming.rb
changes to metaprogramming. NECB has no building specific classed to be used as it is now generalized for all building.
=> removed necb references from metaprogramming

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
air_loop_hvac_apply_single_zone_controls adds EMS code that depends on the zone outdoor air schedule.  Previously, this schedule was getting adjusted by downstream measures per the zone occupancy schedules.  This invalidated the EMS controls in some climate zones with economizer controls.  This change moves the method to be applied last in the air_loop_hvac_apply_standard_controls method so that this EMS code isn't invalidated.
=> move single controls to last method in air_loop_hvac_apply_standard_controls

openstudio-standards.gemspec
the rake & bundler lines are needed for 3.x*. For the rest including using pessimistic version constraints, up to you.
*Not really needed in the sense that it's a development_dependency, so it'll work for us, but since you'll be switching to ruby 2.5.5 soon, might as well update as well.
=> Bump dependencies (OpenStudio-update-gems)

data/geometry/ASHRAE9012013MediumOfficeDetailed.osm, data/geometry/ASHRAELargeOfficeDetailed.osm, data/geometry/ASHRAEMediumOfficeDetailed.osm, data/geometry/ASHRAESmallOfficeDetailed.osm
Hi Matt,
Large office detailed had a handful of small surfaces causing issues when testing the ground FC factor updates. Upon inspection, these surfaces had incorrect outside boundary conditions (see attached screenshot). They were incorrectly flagged as having an outside boundary condition to Ground. I corrected them in this pull request.
=> Correct surfaces 190, 515, and 516 in ASHRAELargeOfficeDetailed.osm

lib/openstudio-standards/standards/Standards.Model.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
This PR updates the WWR adjustment for the Appendix G 90.1-2019 baseline model creation. It adjusts the WWR for all spaces of each building area type to match the requirements in G3.1.1-1 while adjusting it proportionally based on the proposed building window area distribution.
The unit test was updated to include the following steps:
- It now assigns a different standard space type to one of the space
- Run a sizing run to generate the SQL database
- Query the database for get the whole building adjusted WWR
- Compare it with the expected value 
The SRR adjustment method doesn't need to be adjusted as the rules for 90.1-2013 and 90.1-2019 are the same and are already implemented.
=> [90.1-AppG] Update WWR adjustment

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
Proposed changes remove all daylighting control objects for the 90.1-2019 PRM appendix G baseline and onward. Test was updated accordingly.
=> [90.1-AppG] Remove daylighting control objects in baseline

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/Standards.Model.rb, test/90_1_prm/test_appendix_g_prm.rb
The proposed changes handle the generation of multiple baseline models based on orientation:
* Proposed model orientation
* Proposed model orientation + 90 degrees
* Proposed model orientation + 180 degrees
* Proposed model orientation + 270 degrees
The change in orientation is done via a new method `model_rotate()` located in `Standards.Model.rb` but is general enough to be used by any project.
The proposed changes use the `BTAP::FileIO::deep_copy()` method. I'm checking with @mdahlhausen to see if it is okay to use it in this section of the code. I tried other Ruby native approaches to create copies (`dup`, `clone`, or even `Marshal.dump()`) but none worked. Using `deep_copy()` from BTAP seemed to be the most straightforward approach without having to use another gem.
I did not update …
=> Multiple orientations for baseline model(s)

lib/openstudio-standards/standards/Standards.Model.rb
This gets the exisiting schedule limits type in the model and resets the limits to the openstudio-standards default.
This will avoid issue #821 some users were facing when using the create baseline building measure.  If the schedule type limits was already defined, the model would not make a new one, but this may cause a failure if the baseline system included a hot water loop with temperatures above the baseline models limits.
=> always reassign limits on temperature schedule limits to match default

lib/openstudio-standards/standards/necb/NECB2011/qaqc/necb_qaqc.rb
Set the fuel name of sql results to fueloilno2 if the results say additional_fuel and there is a boiler in the file with fueloilno2 fuel type.
=> Improved qaqc.json reporting for fueloilno2

lib/openstudio-standards/prototypes/common/buildings/Prototype.Hospital.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeHotel.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/ashrae_90_1_2013.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/nrel_zne_ready_2017/nrel_zne_ready_2017.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/ze_aedg_multifamily/ze_aedg_multifamily.Space.rb, lib/openstudio-standards/standards/deer/deer_2014/deer_2014.Space.rb, lib/openstudio-standards/standards/deer/deer_2015/deer_2015.Space.rb, lib/openstudio-standards/standards/deer/deer_2017/deer_2017.Space.rb, lib/openstudio-standards/standards/deer/deer_2020/deer_2020.Space.rb, lib/openstudio-standards/standards/deer/deer_2025/deer_2025.Space.rb, lib/openstudio-standards/standards/deer/deer_2030/deer_2030.Space.rb, lib/openstudio-standards/standards/deer/deer_2035/deer_2035.Space.rb, lib/openstudio-standards/standards/deer/deer_2040/deer_2040.Space.rb, lib/openstudio-standards/standards/deer/deer_2045/deer_2045.Space.rb, lib/openstudio-standards/standards/deer/deer_2050/deer_2050.Space.rb, lib/openstudio-standards/standards/deer/deer_2055/deer_2055.Space.rb, lib/openstudio-standards/standards/deer/deer_2060/deer_2060.Space.rb, lib/openstudio-standards/standards/deer/deer_2065/deer_2065.Space.rb, lib/openstudio-standards/standards/deer/deer_2070/deer_2070.Space.rb, lib/openstudio-standards/standards/deer/deer_2075/deer_2075.Space.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
use climate_zone = model_standards_climate_zone(space.model) directly in the method instead of requiring it as an input argument
=> move climate zone to within space_daylighting_control_required? method

lib/openstudio-standards/standards/necb/ECMS/data/boiler_set.json, lib/openstudio-standards/standards/necb/ECMS/data/curves.json, lib/openstudio-standards/standards/necb/ECMS/data/furnace_set.json, lib/openstudio-standards/standards/necb/ECMS/data/shw_set.json, lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb, test/necb/unit_tests/expected_results/boiler_efficiency_modification_expected_results.json, test/necb/unit_tests/tests/test_necb_shw.rb
Also, changing code for boiler and furnace efficiency ECMs so that they can accept a string and a hash.  When a string is passed to the:
modify_boiler_efficiency,
modify_furnace_efficiency, or
modify_shw_efficiency
methods the method looks for the string in the associated boiler_set.json, furnace_set.json, or shw_set.json files in the "name" field.  If the string matches the "name" field in the json it takes the performance information from the file and uses that to set the efficiency and part load curve.  A hash containing the performance information can still be passed to the above methods and they will adjust the performance of the associated equipment to match what is in the hash.
=> Including code for SHW tank efficiency ECM

lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
@asparke2  fixed the NECB JSON loading code for use in the OpenStudio CLI in this commit: https://github.com/NREL/openstudio-standards/commit/de4e210c
@phylroy overwrote that change to its prior state in this commit:
https://github.com/NREL/openstudio-standards/commit/f0fb3009
This commit reimplements the changes @asparke2 made.
=> revert the changes to CLI loading of NECB standards

lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/Standards.ThermalZone.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Space.rb, test/90_1_prm/data/space_envelope_areas.json, test/90_1_prm/test_appendix_g_prm.rb
After checking with the 90.1-2019 PRM development team regarding which space conditioning type should be used for the baseline model (we noticed that the space conditioning can change after assigning baseline internal load assumptions), it was decided to assume that the baseline space conditioning be the same as the proposed/user model.
A `TODO` was added as a reminder to take into account addendum db when adding rules for 90.1-2022 Appendix G.
The proposed changes also include a change in the default infiltration method from `Flow/Area` to `Flow/ExteriorWallArea` (more reasonable assumption). Changes also include a check to only count space floor area of non-unconditioned spaces that have non-zero surface area with outside boundaries set to outdoors (i.e. core spaces are excluded from …
=> [Appendix G] Update the infiltration calculations

data/geometry/ASHRAESmallDataCenter.json
Super minor update on the data center model.  @mdahlhausen 
So that both CRAC (small DC) and CRAH (large DC) are able to adjust AHU supply air flow rate based on CPU load.
=> Update the small data center CRAC fan type from CAV to VAV

lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/Standards.SubSurface.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Space.rb, test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
The proposed changes add a new 90.1-PRM method to adjust the skylight-to-roof ratio of the baseline model. The existing method was based on the 90.1-2010 PRM user manual which is different from the 90.1-2019 PRM. A "SRR" test was also added.
=> Update SRR adjustment

lib/openstudio-standards/prototypes/common/buildings/Prototype.HighRiseApartment.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.MediumOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SecondarySchool.rb
In EnergyPlus 9.4 (OS 3.1.0), the output variable for `ElectricEquipment` changed from `Electric Equipment Electric Energy` to `Electric Equipment Electricity Energy`.  openstudio-standards was creating a `Meter:CustomDecrement` to feed a `Transformer`, so this PR adds a switch statement to use the correct variable name depending on the version of OpenStudio being used.
This should have no impact on simulation results.
=> Version-specific electric equipment output variable for E+ 9.4 change

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
Replaces hard-coded `0.15` AirLoopHVAC occ threshold with `air_loop_hvac_unoccupied_threshold()` return.
Right now, the occupancy threshold for motorized dampers is hard-coded to `0.15`.  Change this to instead pull the threshold from  the method `air_loop_hvac_unoccupied_threshold()` so that this threshold can be overwritten consistently by derivative classes.  Currently, `air_loop_hvac_unoccupied_threshold()` returns `0.15`, so this should not impact any of the prototypes.
=> Replaces hard-coded 0.15 AirLoopHVAC occ threshold

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
this defaults to no hot water loop if heating fuel is nil and adds a check with logging message in the model_get_or_add_hot_water_loop method
Fixes #969
=> account for doas systems with no heat the default method builds a hot water loop with no heating equipment

lib/openstudio-standards/standards/Standards.SpaceType.rb
space_type_get_standards_data returns an empty {} if the lookup fails.  add a check if space_type_properties is empty as well.
Addresses #977
=> Add check if space_type_properties is empty

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.ext_ltg.json
- parking LPD updated based on values derived from [2015 LMC report](https://www.energy.gov/eere/ssl/2015-us-lighting-market-characterization)
- entry canopy LPD was also udpated based on updates already made on DEER pre1975 to 1996
- refer to [summary slide deck](https://nrel.sharepoint.com/:p:/r/sites/LoadProfiles/Shared%20Documents/05%20Calibration/4%20Calibration%20and%20Validation/ComStock_Lighting_Analysis/LightingPowerDensity/201207_ExteriorLightingPowerDensityFromDataSources.pptx?d=we753e224cdc04daea774e80bf4409a63&csf=1&web=1&e=0beiZO) for details
=> exterior (parking and entry canopy) lighting power density update

data/standards/manage_OpenStudio_Standards.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/data/ashrae_90_1_2007.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/data/ashrae_90_1_2010.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/data/ashrae_90_1_2013.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/data/doe_ref_1980_2004.heat_rejection.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/data/doe_ref_pre_1980.heat_rejection.json
Hi Jeremy,
I have updated heat rejection performance metrics for 90.1 2016/2019 based on Table 6.8.1-7.  This also includes updated default performance for Dry Coolers
=> Heat rejection updates

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/ashrae_90_1_2013.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/ashrae_90_1_2016.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb
The ERV exception to Section 6.5.3.3 in 90.1-2010/3 has been removed in 90.1-2016/9. The proposed changes remove that section in the code applicable to 90.1-2016/9 and add a comment that refers to this exception in the code applicable to 90.1-2013 and 90.1-2010. Additional information in Section B1.2.3 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2016 report](https://www.energycodes.gov/energy-savings-analysis-ansiashraeies-standard-901-2016).
=> Remove ERV exception for MZ VAV optimization

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.economizers.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.economizers.json
Table 6.5.1.2 (minimum fan cooling unit size for which an economizer is required for computer room) from 90.1-2013 has been removed in 90.1-2016/9. Economizer are now required for all climate zones except in climate zone 0/1 A/B. Additional information in Section B1.2.2 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2016 report](https://www.energycodes.gov/energy-savings-analysis-ansiashraeies-standard-901-2016).
=> Update economizer threshold

lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.Model.rb, lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2013/ashrae_90_1_2013.Model.rb, lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2016/ashrae_90_1_2016.Model.rb, lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Model.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.FullServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeHotel.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.PrimarySchool.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.QuickServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SecondarySchool.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Fan.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.FanZoneExhaust.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
The proposed changes add transfer air for non-kitchen spaces, when applicable, as per Section 6.5.7.1 in 90.1-2016/9. Additional information regarding the 90.1-2016/9 implementation are provided in Section B1.2.1 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2016 report](https://www.energycodes.gov/energy-savings-analysis-ansiashraeies-standard-901-2016).
=> Add transfer air for non-kitchen spaces

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.motors.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.motors.json
90.1-2016 incorporates changes to the federal standards which includes motor efficiency, the proposed changes reflect these changes: increase of minimum efficiency of large motors above 200 nameplate HP.
=> Update motor efficiency requirements

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.construction_properties.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.construction_properties.json
The proposed changes update the minimum code requirements for opaque doors for ASHRAE 90.1-2016/9. Additional information regarding the 90.1-2016/9 implementation are provided in Section B1.1.4 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2016 report](https://www.energycodes.gov/energy-savings-analysis-ansiashraeies-standard-901-2016), note that this sections mentions adding doors to the prototypes which was added by #678.
=> Update opaque doors U-factor minimum code requirements

lib/openstudio-standards/prototypes/common/buildings/Prototype.Hospital.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Outpatient.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
setZoneMinimumAirFlowMethod was deprecated in 3.1. setZoneMinimumAirFlowInputMethod is the new method.  Adding the deprecated method for pre OS v3.1 compatibility
=> add version toggle for deprecated setZoneMinimumAirFlowMethod

test/circleci_tests.txt, test/necb/unit_tests/tests/test_daylighting_sensor_control.rb, test/necb/unit_tests/tests/test_ecm_chiller.rb, test/necb/unit_tests/tests/test_ecm_scaling_loads.rb, test/necb/unit_tests/tests/test_led_lighting.rb, test/necb/unit_tests/tests/test_nv.rb, test/necb/unit_tests/tests/test_pv_ground.rb
updated inputs for sizing_run_dir in pv_ground, nv, loads scaling, and advanced chiller ecms; removed sizing_run_dir from daylighting sensor controls and led lighting ecms as it was not needed; updated nv ecm and its expected results file to only run tests for necb2017 for making it faster
=> nrcan 321- Fixing PV, NV, VSD chiller, and loads scaling tests

lib/openstudio-standards/utilities/simulation.rb
Disables HVAC Sizing Simulations for Sizing Periods after running a sizing run.  If this isn't disabled, READVARSESO will export both the annual timeseries AND the timeseries for the HVAC sizing periods, which breaks ComStock output reporting.  The downside to disabling this after the sizing run is that some of the sizes calculated for the autosized plant equipment which use this flag will then change during a later annual simulation, which could be confusing.  An alternate approach would be to adjust this in ComStock model creation measures separately from openstudio-standard.  @mdahlhausen I'll make a PR into ComStock using that approach and if we like this approach of doing in openstudio-standards better we can use this instead.
=> Disables HVAC Sizing Simulations for Sizing Periods after running a sizing run

Rakefile, data/standards/manage_OpenStudio_Standards.rb, docs/DeveloperInformation.md, openstudio-standards.gemspec
Updates the gemspec to remove the google-api-client gem and its dependencies.  Uses the newer google_drive gem instead.
Also update rubyXL and nokogiri, which @ckirney raised has having security issues with the older versions.
Luckily, the google_drive gem is much simpler than the older version, so this was an easy refactor that got rid of a decent chunk of code.
=> Gem update

lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
This is done so that the check includes subclasses of 'Numeric' and 'String' types.
=> Using 'kind_of?' statement instead 'instance_of?' statement.

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/comstock_ashrae_90_1_2016/data/comstock_ashrae_90_1_2016.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/comstock_ashrae_90_1_2019/data/comstock_ashrae_90_1_2019.ext_ltg.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_1985/comstock_deer_1985/data/comstock_deer_1985.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_1996/comstock_deer_1996/data/comstock_deer_1996.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2003/comstock_deer_2003/data/comstock_deer_2003.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2007/comstock_deer_2007/data/comstock_deer_2007.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2011/comstock_deer_2011/data/comstock_deer_2011.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2014/comstock_deer_2014/data/comstock_deer_2014.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2015/comstock_deer_2015/data/comstock_deer_2015.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_2017/comstock_deer_2017/data/comstock_deer_2017.ext_ltg.json, lib/openstudio-standards/standards/deer/deer_pre_1975/comstock_deer_pre_1975/data/comstock_deer_pre_1975.ext_ltg.json
- this update is from EULP enduse data analysis
- summary slide deck is located in [here](https://nrel.sharepoint.com/:p:/r/sites/LoadProfiles/Shared%20Documents/05%20Calibration/4%20Calibration%20and%20Validation/ComStock_Lighting_Analysis/LightingPowerDensity/201207_LightingPowerDensityFromDataSources.pptx?d=we753e224cdc04daea774e80bf4409a63&csf=1&web=1&e=cSmkV7)
- LPDs for exterior parking lot are revisited based on the latest buildstock.csv including the latest building population
- not going to make huge difference in the simulation results but this update is to use the same approach that was used before but with updated input data to match weighted average of LPDs in models against LMC report's national average (0.04103 W/ft2).
- values are updated on both 90.1 and DEER standards as …
=> exterior parking lpd update based on updated building population

lib/openstudio-standards/prototypes/common/buildings/Prototype.FullServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Hospital.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeHotel.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.PrimarySchool.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.QuickServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SecondarySchool.rb
Per addendum BR of 90.1 2019. efficiency values of freezer and reach-in refrigerator are updated. Incorrect default values in certain prototypes are modified.
Energy Savings Analysis: [ANSI/ASHRAE/IES Standard 90.1-2019 report](https://www.energycodes.gov/sites/default/files/2021-07/20210407_Standard_90.1-2019_Determination_TSD.pdf) does not contain a dedicated section for Addendum BR because the impacted refrigerators and freezers are federally-regulated.
=> Freezer and reach-in refrigerator efficiency update

data/standards/manage_OpenStudio_Standards.rb, data/standards/metadata_units_OpenStudio_Standards-ashrae_90_1.csv, lib/openstudio-standards/standards/Standards.CoilHeatingGas.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/data/ashrae_90_1_2007.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/data/ashrae_90_1_2010.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/data/ashrae_90_1_2013.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.boilers.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/data/doe_ref_1980_2004.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/data/doe_ref_pre_1980.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/nrel_zne_ready_2017/data/nrel_zne_ready_2017.furnaces.json, lib/openstudio-standards/standards/ashrae_90_1/ze_aedg_multifamily/data/ze_aedg_multifamily.furnaces.json
The proposed changes includes two changes: 
1) Update 90.1-2019 boilers to use the correct 84% minimum annual fuel utilization efficiency in high capacity boilers
2) Update the 90.1 2004-2019 furnace gas heating coils to use their respective minimum efficiency values (based on year and capacity), updated with relevant documentation. This required adding json files for furnaces to the repository and workflow.
For more information regarding the motivation for this update, consider looking into [Addendum 90.1-2019 BP and Addendum 90.1-2019 BO](https://www.ashrae.org/file%20library/technical%20resources/standards%20and%20guidelines/standards%20addenda/90.1-2016/90_1_2016_be_bm_bn_bo_bp_br_bs_bu_bv_cf_cl_cm_cq_ct_cu_cv_cw_cy_20210324.pdf).
=> Update furnace and boiler efficiency to match values from ASHRAE 90.1-2004 through 2019

lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.hvac_systems.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
To implement Addendum A of 90.1 2016, the maximum OA fraction for single-zone systems is changed from 0.7 to 0.75 to reflect lower damper leakage requirement changes.
The proposed changes include:
1. rearrange the code snippet of adding maximum OA fraction schedule for single-zone systems ahead of supply fan check code in the single zone control method to avoid certain single-zone systems not having this schedule. This impacts all code versions.
2. extract the maximum OA fraction schedule code into a dedicated method and override it in the 90.1 2019 subclass to use 75% OA max fraction.
For more information, check Section B.2.1  in the Energy Savings Analysis: [ANSI/ASHRAE/IES Standard 90.1-2019 report](https://www.energycodes.gov/sites/default/files/2021-07/20210407_Standard_90.1-2019_Dete …
=> Single zone system maximum OA fraction for damper leakage rage

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb
Addendum AP of 90.1 2016 further details exceptions for multi-zone VAV system SAT reset requirements. The additional exemptions are implemented as:
1. Differentiate exceptions between climate zones (0A, 1A and 3A) and (2A).
2. Add design OA requirements for these two groups of exceptions.
3. Add ERV and design OA ratio check for additional exception.
For more information check Section B.2.6 in the Energy Savings Analysis: [ANSI/ASHRAE/IES Standard 90.1-2019 report](https://www.energycodes.gov/sites/default/files/2021-07/20210407_Standard_90.1-2019_Determination_TSD.pdf).
=> Multizone VAV supply air temperature reset exceptions

lib/openstudio-standards/hvac_sizing/Siz.Model.rb, lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb
Also removing blank spaces from new object names when changing furnace, shw, and boiler efficiency.
=> Removing blank spaces from start and end of object names when getting autosized values

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.prototype_inputs.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/data/ashrae_90_1_2007.prototype_inputs.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/data/ashrae_90_1_2010.prototype_inputs.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/data/ashrae_90_1_2013.prototype_inputs.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.prototype_inputs.json, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.prototype_inputs.json
The proposed changes remove the value from `main_water_heater_space_name` for the high-rise apartment so a scheduled ambient temperature is used instead (expected behavior). The current value to `main_water_heater_space_name` prevents the temperature schedule from being created.
=> Fix high-rise apartment water heater ambient temperature

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/ashrae_90_1_2004.Model.rb, test/doe_prototype/test_small_office.rb
The construction search in 90.1-2004 depends on min & max percent of surface.
The fix introduces a new workflow that added a new method called model_get_percent_of_surface_range, and it enables flexibility in identifying construction based on window to wall ratio by adding two search criteria: minimum_percent_of_surface and max_percent_of_surface.
The default behavior of this function returns nil for both min&max percent of surface. The detail implementation shall be overriden in the each individual routine (90.1-2004).
Add 90.1-2004 to test_small_office test set.
Tests has run locally for All ASHRAE prototype & baseline.
=> Implement new workflow to search constructions.

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
ZoneVentilationDesignFlowRate::setDesignFlowRateCalculationMethod has been deprecated. The proposed changes remove calls to this methods to avoid unnecessary warnings.
=> Remove setDesignFlowRateCalculationMethod

lib/openstudio-standards/standards/Standards.Space.rb
Scraping of log files helped identify that a skylight in space Gym_ZN_1_FLR_1 (primary school) is non-rectangular. This issue appears to occur in all the climate zones and for all the code versions. Standards.Space.rb was revised to fix this issue.
=>  fix non-rectangular skylight issue 

data/geometry/ASHRAEHighriseApartment.osm
An evaporator fluid cooler object was included in the geometry template file for the high-rise apartment prototype. This objects is unattached, and therefore untranslated to the file IDF but it does generate unnecessary warnings related autosized design values.
=> Remove fluid cooler object from geometry template

lib/openstudio-standards/standards/Standards.CoilHeatingGas.rb
The proposed change add a guard clause to not lookup efficiency for coils with no capacity. The current code will post a warning stating that the efficiency cannot be looked-up which can be confusing because it doesn't specify why.
=> Furnace efficiency lookup for coils without capacity

lib/openstudio-standards/standards/Standards.Model.rb
The AirLoopHVACDedicatedOutdoorAirSystem object was added in OS v3.2.0.  Remove these objects as part of the model_remove_prm_hvac() method.
Address issue #1226
=> remove AirLoopHVACDedicatedOutdoorAirSystem in remove method

data/standards/export_OpenStudio_libraries.rb, lib/openstudio-standards/hvac_sizing/Siz.ThermalZone.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.BoilerHotWater.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.ThermalZone.rb
Add handling for propane as a heating fuel type accounting for the fuel name adjustments in #1100
=> add handling for propane

lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb
Fixes issue #1295 by using older ruby syntax before version 2.6.
@ckirney @khaddad just making you aware of this fix I made to standards.  Please avoid using the newer endless range syntax in ruby if you can accomplish the same thing with older syntax.
=> implement pre ruby 2.6 method for slicing

data/geometry/ASHRAECollege.osm
Added TZ prefix to college thermal zone names to prevent identical naming to spaces which causes issues with the new E+ version
=> add prefix to college thermal zone names

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
This fixes a bug where if a user enters 'Gas' or 'NaturalGas' for the main_heat_fuel argument in model_add_hvac_system for a 'PSZ-AC' system type, and does not change the default air_loop_heating_type: 'Water', the method will add an empty hot water loop to the model and construct the PSZ-AC system with gas coils.
Fixes issue #1306.
=> Change heating type if using a hot water loop with a PSZ-AC system

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.SpaceType.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb, test/90_1_general/test_get_building_climate_zone_and_building_type.rb
Changes the model_get_building_climate_zone_and_building_type(model) method to model_get_building_properties(model) and returns the standards template as well if available.  Edit the model_find_target_eui(model) method tree to use the model template if available instead of the template used to build the Standards object.
=> Lookup model standards template for model_find_target_eui(model)

test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
Check if correct  VAV fan part load curves from appendix g Table G3.1.3.15 is applied to baseline.
=> check vav part load curve

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.ThermalZone.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/docs/unmet_load_hours.md, test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
The proposed changes add a set of verification to make sure that both the user and baseline model(s) meet section G3.1.2.3 of ASHRAE 90.1 Appendix G. Adjustments are made to the baseline model if the first version of the model ends up having unmet load hours (UMLH). The adjustment follow the recommendation from the ASHRAE 90.1-2019 PRM Reference Manual.
=> Check user and baseline model(s) UMLH

lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.spc_typ.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.spc_typ.json
pre 2004 vintages for small hotel elevator core didn't have a schedule set.  This adds the always off schedule, matching the other vintages.
=> always off schedule comstock small hotel elevator

lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb
From PRM-RM:
Software shall bring the first boiler to 100% capacity prior to the staging of the next boiler.
When more than one chiller is required in the baseline design, each chiller shall run to full capacity prior to staging of the next chiller. When more than one chiller is operational, then the load shall be shared equally among all the chillers.
The current boiler's setting is correct and the chiller's setting is updated from 'SequentialLoad' into 'SequentialUniformPLR'.
=> update chiller staging method

lib/openstudio-standards/prototypes/common/objects/Prototype.SizingSystem.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/doe_ref_1980_2004.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/doe_ref_pre_1980.AirLoopHVAC.rb
Fixes VRP enumerations for newer E+ versions and makes Evz template-dependent. Fixes #1372 using the method suggested by @lymereJ. Opened a separate feature request issue #1391 to someday use EnergyPlus to autosize minimum damper position.
=> Fixes VRP enumerations for newer E+ versions and makes Evz template-dependent

lib/openstudio-standards/standards/Standards.ThermalZone.rb
The heatingSetpointTemperatureSchedule method for the ZoneHVACLowTemperatureRadiantElectric object returns a Schedule object, not an optional Schedule object.  Fixes #1338
=> fix schedule method for heatingSetpointTemperatureSchedule

lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.rb, test/90_1_prm/test_appendix_g_prm.rb
The command line interface is failing when calling create PRM method.
Failing message indicates the directory for user data files are arrays instead of strings.
Fix the issue in the convert_user_data_to_json function, and verified the workflow in the command line.
=> Appendix g dev debug user directory error

lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb
```diff
-OS_AirLooHVAC_UnitarySystem
+OS_AirLoopHVAC_UnitarySystem
```
View without whitespace changes: https://github.com/NREL/openstudio-standards/pull/1418/files?w=1
=> Typo in OS_AirLoopHVAC_UnitarySystem in Siz.HeatingCoolingFuels

lib/openstudio-standards/btap/btap.model.rb, lib/openstudio-standards/btap/envelope.rb, lib/openstudio-standards/standards/Standards.Construction.rb
change methods to use find_and_set_insulation_layer instead of find_and_set_insulaton_layer (misspelled), and delete all instances  of find_and_set_insulaton_layer (misspelled)
=> fix typo and delete extra methods

lib/openstudio-standards/standards/Standards.BoilerHotWater.rb, lib/openstudio-standards/standards/Standards.PlantLoop.rb
- Fix #230
- Update to PRM method to have better naming for boilers
- Re-apply efficiency standard because multiple boilers with lower capacity may have different efficiency standards at the smaller size
=> change prm boiler naming

lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb
Add check for plant loop cooling fuels for 'OS_HeatExchanger_FluidToFluid' objects.  Fixes issue #754
=> support OS_HeatExchanger_FluidToFluid in fuels

lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Pump.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.PumpVariableSpeed.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/Standards.AirTerminalSingleDuctParallelPIUReheat.rb, lib/openstudio-standards/standards/Standards.Fan.rb, lib/openstudio-standards/standards/Standards.Pump.rb, lib/openstudio-standards/standards/Standards.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.ZoneHVACComponent.rb, lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb
Fixes #109, checking hard-sized values before autosized values anywhere size checking appears in the code.
=> check hard-sized values before autosized values

lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb, test/os_stds_methods/models/basic_pthp_model.osm, test/os_stds_methods/test_apply_hvac_efficiency_standard.rb
90.1-2016 and 90.1-2019 PTHP systems don't use the pthp_cop_coefficient_1, pthp_cop_coefficient_2 coefficients as earlier versions.  Add a check that they are present for earlier standards.
=> check PTHP cop coefficients

lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb
One way to verify the issue is to use 'bldg_2' from test/90_1_prm which has the required Maximum Fraction of Outdoor Air Schedule assigned to a multizone AHU. I wrote a simple unit test to show the method returning true, but not sure if it's needed.
=> fix for Issue 1502

lib/openstudio-standards.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlanarSurface.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Surface.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.rb, lib/openstudio-standards/utilities/assertion.rb
We discover one issue with a sample model below (change the txt to osm to test)
[sample_med_os_ad1.txt](https://github.com/NREL/openstudio-standards/files/11426666/sample_med_os_ad1.txt)
The model does not have defaultConstructionSet assigned to space, spaceType, building or even model. However, it does run successfully.
This causes our code failure when searching for the [defaultConstructionSet ](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlanarSurface.rb#L33-L58)to fill up empty construction.
The failure cause EnergyPlus simulation failure due to missing construction name.
I suggest to handle this as assertion instead of return empty hashmap - give enough information for user to debug their model.
=> Wx bug fix fenestration expansion missing construction name

lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, test/90_1_prm/test_appendix_g_prm.rb
reorganize the exterio lighting function to split the user data reading from the PRM data setting.
=> add exterior lighting test function

lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb
**background**
- noticed there is a line like this below when calculating `Vertical Height used for Piping Correction Factor` for `AirConditioner:VariableRefrigerantFlow` object
```
max_net_vert_distance = [max_net_vert_distance, 0.000001].max
```
- which was not letting `max_net_vert_distance` to be a negative value
- but EP [documentation example](https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-vertical-height-used-for-piping-correction-factor-000) shows `max_net_vert_distance` can be a negative value. for example, if your VRF outdoor unit is located on the roof, and all of your indoor units are below the roof, `max_net_vert_distance` becomes a negative value.
**change summary**
- so this change is basically …
=> VRF outdoor unit max_net_vert_distance calculation

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
Fixes tests on develop as Vector3d.new no longer allows array arguments.
=> explicitly pass x, y, and z values instead of array of values

lib/openstudio-standards/utilities/simulation.rb
This change makes the messages for the start and end of a simulation consistent with one another and include timestamps. Both of these help with runtime profiling.
=> Simulation time profiling

lib/openstudio-standards/space/space.rb, test/modules/space/test_space.rb
The method spaces_get_occupancy_schedule would error if there was a space with no people in it. Occurs somewhat frequently in models where each space is individually passed to the method.
=> Return zero schedule when no people in space from spaces_get_occupancy_schedule

lib/openstudio-standards/standards/Standards.PlantLoop.rb, test/90_1_prm/models/bldg_4.osm
- use 'OS_DistrictHeating_Water', 'OS_DistrictHeating_Steam', not 'OS_DistrictHeatingWater', 'OS_DistrictHeatingSteam'
- fix surface matching issue in bldg_4 test model by making offending surfaces adiabatic
=> Fix OS3.7 DistrictHeating lookup

lib/openstudio-standards/weather/information.rb
Use __dir__ instead of Dir.pwd for running with the CLI
- Fixes #1815
=> Change current directory for CLI

openstudio-standards.gemspec
These were needed for google drive spreadsheets and are no longer used.
=> Remove aes, rest-client, and roo gem dependencies

lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.SpaceType.rb, test/90_1_prm/prm_check.rb
`space_lighting_per_area = (lighting_per_length * space_height) + lighting_per_area` is dimensionally inconsistent. Need to divide by area to get W/m2. This was @dmaddoxwhite's suggestion. Fixes #1506.
=> Correct prm lighting calculation

lib/openstudio-standards/schedules/information.rb
Fix a floating point error in the test by rounding the schedule values
=> Fix floating point error in schedule_day_get_hourly_values

test/necb/unit_tests/expected_results/ceiling_test_expected_results.json, test/necb/unit_tests/expected_results/qaqc_report_expected_result.json
The pretty_generate method in the rubygem  json 2.8.1 changed the default formatting for empty brackets versus what was in earlier json gem versions
Minor fix to NECB CI testing.
This will not be exhaustively relevant to every PR.
=> Update NECB CI .json format
