openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ChillerElectricEIR.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ScheduleConstant.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ScheduleRuleset.rb, openstudio-standards/test/test_annual_min_max_value.rb
Would be nice to have this in gem for 1.11.1 OpenStudio.
=> setting climate zone and building type

openstudio-standards/lib/openstudio-standards/hvac_sizing/HVACSizing.PumpVariableSpeed.rb
=> Corrected typo for Pump autosizedRatedPowerConsumption

openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb
I'll make a commit to QAQC measures to extend the test to include small office prototype.
=> Tested in GUI with small office

openstudio-standards/Rakefile, openstudio-standards/lib/openstudio-standards.rb, openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb, openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.Model.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb
I merged all of @jmarrec s pull requests into this branch and fixed conflicts.
=> Merge julien prs

openstudio-standards/lib/openstudio-standards.rb, openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb, openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.Model.rb
Added correct classification of Water Source Heat Pumps as being potentially Hybrid if serves by hot water loop. And added check for plant loop with heat exchanger
=> Correct classification of WSHP, and check for HX connected to boiler on secondary PL

openstudio-standards/lib/openstudio-standards/prototypes/Prototype.outpatient.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXTwoSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb
=>  Change iddObjectType for Coils #78

openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb, openstudio-standards/lib/openstudio-standards/hvac_sizing/Siz.ThermalZone.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ThermalZone.rb
Merges baseline fixes which should enable 90.1-2010
=> Baseline fixes 3

openstudio-standards/lib/openstudio-standards/btap/btap.rb, openstudio-standards/lib/openstudio-standards/version.rb
Removes experimental code requiring IRB, which causes issues for some users
=> Fix issue 120

openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ThermalZone.rb
- fix units for `oa_for_volume`
- fix leaving condenser water temp determination
=> Miscellaneous code fixes

openstudio-standards/lib/openstudio-standards.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.elevators.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.hvac.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.Model.swh.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.hvac_systems.rb, openstudio-standards/lib/openstudio-standards/prototypes/Prototype.utilities.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb, openstudio-standards/lib/openstudio-standards/standards/Standards.ThermalZone.rb, openstudio-standards/lib/openstudio-standards/utilities/sqlfile.rb, openstudio-standards/test/.gitignore, openstudio-standards/test/circleci_tests.txt, openstudio-standards/test/doe_prototype/models/basic_2_story_office_no_hvac.osm, openstudio-standards/test/doe_prototype/test_add_hvac_systems.rb
Adds a bunch of additional HVAC systems
=> Hvac additions

.circleci/config.yml
=> Updating my branch with latest nrcan branch

lib/openstudio-standards/btap/fileio.rb, lib/openstudio-standards/standards/Standards.Construction.rb
adding support for measures to standards directly.
=> made changes for measures work.

lib/openstudio-standards.rb, lib/openstudio-standards/standards/necb/necb_2011/qaqc/qaqc_data/design_supply_temp.json, lib/openstudio-standards/standards/necb/necb_2011/qaqc/qaqc_data/zone_sizing.json, lib/openstudio-standards/standards/necb/necb_2015/necb_2015.rb, lib/openstudio-standards/standards/necb/necb_2015/qaqc/necb_2015_qaqc.rb, lib/openstudio-standards/standards/necb/necb_2015/qaqc/qaqc_data/space_compliance_2015.json, test/necb/test_necb_qaqc.rb, test/necb/test_necb_qaqc_single.rb
BTAP Issues task 48 and 62
* reorganize necb 2011 and 2015 folder structure
* modified which necb 2015 qaqc tests runs
* fix incorrect final qaqc output
* move qaqc methods; minor change to qaqc result wording
* minor changes to qaqc class structure
* rewrite of envelope_compliance for NECB 2015
* sub NECB2011 with NECB2015 & Activated ext-opaque compliance [no changes from 2011]
* Made changes to NECB section numbers for design supply temp
* Update zone sizing NECB section numbers & update which qaqc tests can be run for 2015
* Added space_compliance.json for NECB 2015 QAQC
* space compliance complete... must conduct a full test
* revert small change
=> NECB 2015 QAQC (#352)

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb
https://github.com/canmet-energy/btap_tasks/issues/67
=> fix for '*' for Nil class

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/necb/necb_2011/necb_2011.rb
Fixed standards so btap measures work.
* removed private from standard.model
* added space_type_map acessor to necb base class
* added space mulitplier accessor to necb class
=> Nrcan 71 (#363)

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb
https://github.com/canmet-energy/btap_tasks/issues/79
=> added multipliers for space and subsurface area calculation

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb
* added multipliers for space and subsurface area calculation
https://github.com/canmet-energy/btap_tasks/issues/79
* Added spaces before and after '*'
=> added multipliers for space and subsurface area calculation (#368)

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb, lib/openstudio-standards/standards/necb/necb_2015/qaqc/necb_2015_qaqc.rb
https://github.com/canmet-energy/btap_tasks/issues/51
=> Fix for cannot find values for necb infiltration QAQC

lib/openstudio-standards/standards/necb/necb_2011/building_envelope.rb, lib/openstudio-standards/standards/necb/necb_2011/necb_2011.rb, lib/openstudio-standards/standards/necb/necb_2015/necb_2015.rb
Implementing building geometry scaling function.  This method changes the overall size of the model geometry in the x, y, or z directions (or any combination thereof).  This allows connection use of building scaling measure.
=> Implement geometry scaling in openstudio-standards.

data/geometry/DEER_ERC.osm
=> remove crawlspace from floor area calculation

lib/openstudio-standards/utilities/os_sim_extract.rb
Adding a utility to extract specific data from the simulations.json output file of NRCan OpenStudio PAT AWS runs.
=> Data extraction Utility

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb
https://github.com/canmet-energy/btap_tasks/issues/86
=> Separate qaqc and base data

test/helpers/ci_test_generator.rb, test/necb/test_necb_hvac_system_1.rb, test/necb/test_necb_hvac_system_2.rb, test/necb/test_necb_hvac_system_3.rb, test/necb/test_necb_hvac_system_4.rb, test/necb/test_necb_hvac_system_5.rb, test/necb/test_necb_hvac_system_6.rb, test/necb/test_necb_hvac_system_7.rb
https://github.com/canmet-energy/btap_tasks/issues/121
=> [Nrcan Task 121] Remove funky symbols from the necb Sys_X tests

lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb
https://github.com/canmet-energy/btap_tasks/issues/84
=> [Nrcan Task 84] Fix for Pump sanity check failing on several NECB archetypes

test/circleci_tests.txt, test/necb/models/fsr.osm, test/necb/test_remove_duplicate_materials_and_constructions.rb
https://github.com/canmet-energy/btap_tasks/issues/125
=> [Nrcan task 125] Method to Remove duplicate materials, constructions from model

test/helpers/ci_test_helper/timings.json
https://github.com/canmet-energy/btap_tasks/issues/137
=> Update timing data for CircleCI

lib/openstudio-standards/standards/Standards.Surface.rb
This method searches through the model looking for roofceiling surface types with outside boundary conditions of outdoors.  It selects the outdoor roofs which are highest in the building and then finds the overall centroid of these surfaces.  It returns a hash which includes the centroid of the highest roof(s), the total area of the highest roof(s) and an array of hashes containing the spaces associated with the highest surfaces, and the centroid of highest surface(s) in each of these spaces.
=> Including method find_highest_roof_centre

openstudio-standards.gemspec
This is so that project continues working with Ruby 2.2.4.
=> Freezing roo to version 2.7.1

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
Fixes issue #560
The model was adding internal mass objects to conditioned spaces per a single-use method model_find_conditioned_space_names.  That method gets all system_to_space_map json objects and returns a vector of all spaces under each system in the system_to_space_map.  Sometimes, multiple systems serve the same conditioned space (e.g. unit heater and unit ventilator), so the space would get multiple internal mass objects.
This commit removes the model_find_conditioned_space_names method and instead checks whether a space is conditioned with the space_heated? and space_cooled? methods.
=> Change conditioned spaces checking when adding internal mass

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
@asparke2 merge this commit into the la100 branch too
=> add 'Residential Forced Air Furnace with AC' to systems lookup

lib/openstudio-standards/standards/Standards.Space.rb
=> fix typo that causes issue #598

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb, test/doe_prototype/test_add_exterior_lights.rb
- calculates effective area for doors based on ground floor area, not total area
- minor info/warning/error message changes
- refactors *model_create_exterior_lighting_area_length_count_hash* method per changes detailed in [this commit](https://github.com/NREL/openstudio-standards/commit/941a6c0d905ddd701e19d81e913d2ffab5630030)
=> changes from LA100 branch to exterior lighting methods and tests

data/geometry/ASHRAEWarehouse.osm, docs/Features.md, lib/openstudio-standards/prototypes/common/buildings/Prototype.FullServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.HighRiseApartment.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Hospital.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeHotel.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeOfficeDetailed.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.MediumOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.MediumOfficeDetailed.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.MidriseApartment.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Outpatient.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.PrimarySchool.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.QuickServiceRestaurant.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.RetailStandalone.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.RetailStripmall.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SecondarySchool.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SmallHotel.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SmallOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SmallOfficeDetailed.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SuperMarket.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Warehouse.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb, lib/openstudio-standards/prototypes/common/prototype_metaprogramming.rb
The proposed changes address the fact that the prototypical layout of the skylights not only vary by code versions but also by climate zones.
=> Skylight area variation by climate zones

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
Moves the economizer control EMS inside the fan control if statement.
=> Economizer control EMS only for multispeed configurations

lib/openstudio-standards/prototypes/common/buildings/Prototype.RetailStandalone.rb
Add an EMS if the 90.1-2013 vintage to control the fan and heating coil of the system serving the Front Entry zone.
=> Standalone Retail EMS for Fan and Coil Control

lib/openstudio-standards/prototypes/common/buildings/Prototype.SmallOffice.rb
Update daylighting control sensor location and fraction controlled which varies by code version.
=> Small Office, Update Daylighting Control, Sensor Location and Fraction Controlled

data/geometry/ASHRAE9012010RetailStandalone.osm, lib/openstudio-standards/prototypes/common/buildings/Prototype.RetailStandalone.rb
Updated spaces types, fraction controlled, sensor location and lighting schedule..
=> Standalone Retail, Update Daylighting Control, Sensor Location and Misc. Space Types Assumptions

lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb
I added some logic in the model_add_refrigeration_walkin method to add doorway protection type in walkins
=> Doorway protection type

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
=> don't add economizers to unitary systems

test/doe_prototype/regression_models/LargeOffice-90.1-2013-ASHRAE 169-2013-4A_expected_result.osm
- changed schedule type from constant to hourly for schedules with hourly values
- got rid of extra schedule values in constant schedules
- added missing values in hourly schedules
fyi - some new college model schedules got wrapped into this commit when i rebuilt the jsons
=> fixing schedule inconsistencies with constant/hourly schedules

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
=> Handle CEC climate  zones in model_add_low_temp_radiant method

lib/openstudio-standards/hvac_sizing/Siz.ControllerOutdoorAir.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/Standards.Construction.rb, lib/openstudio-standards/standards/Standards.Fan.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.ScheduleRuleset.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/ashrae_90_1_2004.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.Space.rb
The < and > were causing issues in logs.  Fixes #111.
=> Fix spelling errors in log messages and remove use of < and >

lib/openstudio-standards/btap/hvac.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.SizingSystem.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/necb/NECB2011/hvac_system_1_multi_speed.rb, lib/openstudio-standards/standards/necb/NECB2011/hvac_system_3_and_8_multi_speed.rb, lib/openstudio-standards/standards/necb/NECB2011/hvac_system_6.rb, lib/openstudio-standards/standards/necb/NECB2011/hvac_systems.rb
=> Update deprecated air loop sizing ratio method

lib/openstudio-standards/standards/Standards.SpaceType.rb
rebuild retail store regression models once first test is complete
=> Set additional properties for additional lighting to be all specialty lighting

test/90_1_prm/test_create_prototype_baseline_building.rb, test/circleci_tests.txt
Add test for 90.1-2019 PRM. The test create a DOE prototype building model(s) and its(their) baseline(s). The only assertion currently performed is to check that the baseline is without any error. More assertion will be implemented in the future.
=> 90.1-2019 PRM Test

lib/openstudio-standards/standards/Standards.Model.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
Create dedicated method for stable baseline approach and intermediate method for older method to avoid breaking current OS measure.
=> [90.1-AppG] Dedicated method for stable baseline

lib/openstudio-standards/prototypes/common/prototype_metaprogramming.rb, lib/openstudio-standards/refs/references.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm_2019/ashrae_90_1_prm_2019.Model.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
The proposed changes add a sizing run for the proposed model, add missing class references for the `90.1-PRM-2019` template and update the test to make sure that the sizing goes through.
=> [90.1-AppG] Add sizing run for proposed model

lib/openstudio-standards/standards/Standards.Space.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
Fix path issue in circleci test. Fix data type issue in IsResidential lookup.
=> Apxg set isresidential

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.SpaceType.rb, test/90_1_prm/test_create_prototype_baseline_building.rb
Add lighting for baseline models
=> [AppendixG 90.1 PRM] add lighting for baseline models

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/Standards.SpaceType.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm_2019/ashrae_90_1_prm_2019.Model.rb, test/90_1_prm/test_appendix_g_prm.rb
Add missing YARD docs for new methods.
=> [Appendix G] Add missing YARD docs for new methods

test/necb/unit_tests/expected_results/boiler_efficiency_modification_expected_results.json, test/necb/unit_tests/resources/boiler_test_custom_efficiencies_and_curves.json, test/necb/unit_tests/tests/test_necb_boiler_rules.rb
Including test of code for setting custom boiler efficiency with other boiler tests.
=> Including test of custom boiler efficiency code in boiler unit tests.

lib/openstudio-standards/hvac_sizing/Siz.ZoneHVACTerminalUnitVariableRefrigerantFlow.rb
Fixes an issue with the VRF hardsizing methods, which was identified by @ChristopherCaradonna as part of ComStock work.
=> Fixes VRF terminal hardsizing

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.SpaceType.rb, test/90_1_prm/data/light_occ_sensor.json, test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
The current version considers both day schedule and default schedule. Furthermore, the schedule is able to handle that a schedule is used multiple times.
=> Apxg light occ sensor

lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb
when always_off, resetRefrigeratedCaseRestockingSchedule() and resetRestockingSchedule(), rather than alwaysOffDiscreteSchedule
=> fixed refrigeration restocking schedule bug

lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2013/ashrae_90_1_2013.AirTerminalSingleDuctVAVReheat.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb, lib/openstudio-standards/standards/Standards.AirTerminalSingleDuctVAVReheat.rb, test/doe_prototype/test_add_hvac_systems.rb
minor HVAC fixes identified by Chris Mackey
=> HVAC fixes

lib/openstudio-standards/standards/necb/NECB2011/autozone.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb, test/necb/unit_tests/tests/test_dcv.rb
fixed dcv types flags (replaced spaces and hyphens with underscores) in necb_2011, autozone, and text_dcv
=> fixed dcv types flags in necb_2011, autozone, and text_dcv

lib/openstudio-standards/utilities/simulation.rb
=> Use eplusout.end instead of database for EP status

lib/openstudio-standards/standards/Standards.Model.rb, test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
Add new baseline system type for 2019 Appendix G: constant volume four pipe fan coil.
=> Apxg add sz cv

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Space.rb
The proposed changes update the WWR determination for 90.1-2019 and onward by using the space conditioning type based on sizing run results (loads).
=> WWR determination based on actual space conditioning type

lib/openstudio-standards/standards/necb/NECB2011/lighting.rb
added nil, none, and NECB_Default conditions for lights_type and lights_scale which are related to LED measure in lighting.rb
=> Added nil, none, and NECB_Default options for "lights_type" and "lights_scale"

lib/openstudio-standards/standards/necb/ECMS/pv_ground.rb, lib/openstudio-standards/standards/necb/NECB2011/lighting.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb, test/necb/unit_tests/expected_results/pv_ground_expected_results.json, test/necb/unit_tests/tests/test_pv_ground.rb
revised pv measure and necb2011 to consider building footprint as default area for pv panels, and set necb_default for pv_ground_type as do-nothing for pv measure, and added none option for all args of pv measure
=> Revised ground-mounted PV measure

lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
* updated arguments to support nil and NECB_Default
* fixing scale
* fixing scale
* added defaults to tviz
=> Update from nrcan branch.

lib/openstudio-standards.rb, lib/openstudio-standards/standards/necb/BTAPPRE1980/btap_pre1980.rb, lib/openstudio-standards/standards/necb/ECMS/nv.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb, lib/openstudio-standards/standards/necb/NECB2011/nv.md, test/circleci_tests.txt, test/necb/unit_tests/tests/test_nv.rb
* added natural ventilation measure under the ECMS class, modified necb_2011 and openstudio-standards.rb for natural ventilation measure
* nv.rb is in progress; modified nv args in necb2011
* nv measure is in progress
* nv measure is in progress
* nv.rb is in progress; modified nv args in necb2011
* modified nv-related args in necb_2011.rb
* set nv_type to false in necb_2011.rb
* modified nv-related args in necb_2011, added test code and expected results for nv
* revised nv measure and its test code and expected results file
* added nv-related args to btap_pre1980.rb
* added nv test code to citcleci_tests.txt
* added a documentation for the nv measure
* revised nv.rv and modified necb_2011 for nv-related args
* revised nv.rb and nv.md, modified btap_pre1980.rb for nv-related args
* …
=> Updating again from nrcan branch

lib/openstudio-standards/prototypes/common/buildings/Prototype.HighRiseApartment.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Hospital.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeHotel.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.LargeOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.MediumOffice.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.PrimarySchool.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.SecondarySchool.rb
90.1-2016 incorporates changes to the federal standards which includes low-voltage transformers minimum efficiency.
=> Update transformer efficiency requirements

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
Follow up on #1032, remove adjustments to design days.
=> Remove adjustments to design days

lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
=> correct supply fan lookup

lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
removed extra pv_ground_type arg from model_apply_standard method in necb_2011.rb
=> removed extra pv_ground_type arg

lib/openstudio-standards/standards/Standards.Model.rb
expose hoo_var_method that has always been in gather_inputs_parametric_schedule. This setup to default with hours whitch matches current behaior. I plan to use fractional until logic for hours is more robust to avoid out of oder rules.
=> update model_setup_parametric_schedules with new argument

lib/openstudio-standards/standards/necb/ECMS/nv.rb, lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb, lib/openstudio-standards/standards/necb/NECB2011/nv.md, test/necb/unit_tests/tests/test_nv.rb
revised any caps in args names of the natural ventilation ecm in nv.rb, nv.md, test_nv.rb, and necb_2011.rb
=> revised any caps in args names of the natural ventilation ecm

lib/openstudio-standards/standards/Standards.ThermalZone.rb, test/circleci_tests.txt
=> typo in cooling coil reference

lib/openstudio-standards/standards/Standards.ScheduleCompact.rb
=> fix typo in schedule_compact_annual_min_max_value

lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb, lib/openstudio-standards/standards/necb/NECB2011/autozone.rb, lib/openstudio-standards/standards/necb/NECB2011/beps_compliance_path.rb
Including more changes suggested by rubocop.
=> Fixing bug caused by spelling mistake in ECMS/hvac_systems.rb

lib/openstudio-standards.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/Standards.AirTerminalSingleDuctParallelPIUReheat.rb, lib/openstudio-standards/standards/Standards.Construction.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.PlanarSurface.rb, lib/openstudio-standards/standards/Standards.PlantLoop.rb, lib/openstudio-standards/standards/Standards.ScheduleConstant.rb, lib/openstudio-standards/standards/Standards.ScheduleRuleset.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/Standards.SpaceType.rb, lib/openstudio-standards/standards/Standards.Surface.rb, lib/openstudio-standards/standards/Standards.ThermalZone.rb, lib/openstudio-standards/standards/Standards.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Space.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.rb, lib/openstudio-standards/utilities/array.rb, lib/openstudio-standards/utilities/object_info.rb, lib/openstudio-standards/utilities/schedule_translator.rb
=> Rubocup fixes

lib/openstudio-standards/standards/necb/common/btap_datapoint.rb
remove direct require calls to developer dependencies in btap_datapoint.rb
=> remove redundant dependency calls

openstudio-standards.gemspec
=> Add PNNL team to author list

lib/openstudio-standards.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.AirTerminalSingleDuctParallelPIUReheat.rb, lib/openstudio-standards/standards/Standards.Fan.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.PlantLoop.rb, lib/openstudio-standards/standards/Standards.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Fan.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.FanConstantVolume.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.FanOnOff.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.FanVariableVolume.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.FanZoneExhaust.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb
Address development branch test failures.
=> Address development branch test failures

lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
Addresses https://github.com/NREL/openstudio-standards/issues/1228
Also another minor fix related to https://github.com/NREL/openstudio-standards/issues/987
=> zone unitary fuel check and fan power lookup

lib/openstudio-standards.rb, lib/openstudio-standards/standards/necb/NECB2020/building_envelope.rb, lib/openstudio-standards/standards/necb/NECB2020/service_water_heating.rb
Including envelope changes and SHW changes.
=> Merging NRC NECB2020 changes

lib/openstudio-standards/standards/Standards.Construction.rb
When a target U-value lower than the sum of air films and other construction layers is specified, instead of leaving the insulation layer unchanged (resulting in unreasonably high R-values), throw a warning, but instead of leaving the insulation layer in place untouched, remove the insulation layer from the construction entirely, and name the construction with the actual R-value, which is the sum of the films (if included in the standard, as they are for 90.1) and the other layers.
=> Fixes #1284 by removing insulation for low U-value constructions

lib/openstudio-standards/prototypes/common/objects/Prototype.BoilerHotWater.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
make the temperature inputs to create_boiler_hot_water explicitly in Fahrenheit
Address issue #1121
=> coordinate inputs to create_hot_water_boiler

lib/openstudio-standards.rb, lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb, lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb, lib/openstudio-standards/standards/Standards.AirTerminalSingleDuctParallelPIUReheat.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.AirTerminalSingleDuctParallelPIUReheat.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/docs/vav_parallel_piu_terminals_fan_control.md, test/90_1_prm/data/prototype_list.json, test/90_1_prm/test_appendix_g_prm.rb
The proposed changes update parallel PIU fan control. The changes also include some additional unit tests to check that the correct type of terminal is used in the baseline building along with tests that verify if the secondary airflow is calculated according to the code requirement.
=> Update parallel PIU fan control

lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.spc_typ.json, lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.spc_typ.json
lighting schedule was missing for mechanical and electrical rooms
schedule is always off, which makes sense, but way want to include some rare diversity here with some on sometimes
=> add missing small hotel lighting schedule

lib/openstudio-standards/hvac_sizing/Siz.ThermalZone.rb
The proposed changes fix zone design air flow lookup when no heating or cooling load.
=> Fix zone design air flow lookup when no heating or cooling load

lib/openstudio-standards/standards/Standards.Space.rb, test/circleci_tests.txt, test/os_stds_methods/test_misc.rb
Update space conditioning type for plenums following the PRM-RM recommendations.
=> Update space conditioning type for plenums

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb
The proposed changes set the baseline model space conditioning category based on the proposed model's.
=> Baseline space conditioning category based on the proposed model's

lib/openstudio-standards/standards/Standards.Space.rb
=> Assign space conditioning category for supply air plenums

lib/openstudio-standards/prototypes/common/buildings/Prototype.College.rb, lib/openstudio-standards/prototypes/common/buildings/Prototype.Laboratory.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.CoilCoolingWaterToAirHeatPumpEquationFit.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.Space.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.CoilCoolingDXSingleSpeed.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.CoilHeatingDXSingleSpeed.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Surface.rb
Fixing offences identified by Rubocop.
=> Miscellaneous Rubocop formatting fixes

lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb, test/90_1_prm/test_appendix_g_prm.rb
Update the PRM method arguments.
=> Update the PRM function arguments

Jenkinsfile, Jenkinsfile_develop, lib/openstudio-standards/btap/btap_result.rb, lib/openstudio-standards/btap/economics.rb, lib/openstudio-standards/btap/envelope.rb, lib/openstudio-standards/btap/fileio.rb, lib/openstudio-standards/btap/measures.rb, lib/openstudio-standards/btap/vintagizer.rb, lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, lib/openstudio-standards/standards/Standards.Construction.rb, lib/openstudio-standards/standards/Standards.Model.rb, lib/openstudio-standards/standards/Standards.PlanarSurface.rb, lib/openstudio-standards/standards/Standards.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.ZoneHVACComponent.rb, lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.entryways.json, lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.parking.json, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.AirLoopHVAC.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.Model.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlanarSurface.rb, lib/openstudio-standards/standards/necb/BTAPPRE1980/hvac_system_6.rb, lib/openstudio-standards/standards/necb/ECMS/hvac_systems.rb, lib/openstudio-standards/standards/necb/ECMS/nv.rb, lib/openstudio-standards/standards/necb/NECB2011/hvac_systems.rb, lib/openstudio-standards/standards/necb/NECB2011/qaqc/necb_qaqc.rb, test/90_1_prm/baseline_901_2013_helper.rb, test/90_1_prm/test_create_performance_rating_method_baseline_building - bravache.rb
I may not have caught all of them, but I did catch a few. Tried to maintain backward compatibility.
I tried to make the commits (and their messages) explicit, so it should be redundant to add a review as a walkthrough of my changes, please use each commit to review. Also, lots of whitespace changes (trailing spaces and some tab characters), so if viewing on github add `?w=1` to the url, you'll see it's actually 60 lines changed only: https://github.com/NREL/openstudio-standards/pull/1393/files?w=1
Found via https://github.com/NREL/openstudio-common-measures-gem/pull/121
=> OS SDK 3.5.0 API breaking changes

Jenkinsfile_develop
Simple config change to use updated Jenkins runner.  Tests will now run the following for each branch and/or PR. 
- opentudio:3.2.1. 
- openstudio:develop
=> Update Jenkins Runner 

lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb
=> create temp_sch_type_limits if not generated previously

lib/openstudio-standards/weather/Weather.Model.rb
=> Give a path length warning when loading weather files

lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb, lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.entryways.json, lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.parking.json
temporary data additions so this building type doesn't fail out in extension gem related measures
Should fix #1151
=> add laboratory exterior lighting and entryway data

lib/openstudio-standards/standards/Standards.WaterHeaterMixed.rb, lib/openstudio-standards/standards/necb/NECB2011/service_water_heating.rb, lib/openstudio-standards/standards/necb/NECB2020/service_water_heating.rb
=> fix UA units in info message

lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb, test/doe_prototype/test_laboratory.rb, test/doe_prototype/test_large_data_center_highITE.rb, test/doe_prototype/test_large_data_center_lowITE.rb, test/doe_prototype/test_small_data_center_highITE.rb, test/doe_prototype/test_small_data_center_lowITE.rb
Address issue [#1382 ](https://github.com/NREL/openstudio-standards/issues/1382#issue-1391526756)
=> Fix the bug that small data center test fail on cold climates (CZ6-8).

lib/openstudio-standards/prototypes/common/objects/Prototype.utilities.rb
=> fix issue 1326

lib/openstudio-standards/standards/Standards.SpaceType.rb, lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.SpaceType.rb
Fix issues in lighting schedule duplication and missing lighting power density when standard space type is not one of the PRM standard space type.
=> Appx g/bugfix/duplicate ltg schedules

Jenkinsfile, Jenkinsfile_develop
updates the ci links in the jenkins file.
=> update ci links

lib/openstudio-standards/standards/necb/NECB2011/hvac_systems.rb
Capital TRUE and FALSE are no longer recognized
=> Ruby 3.2.2 release fix

lib/openstudio-standards/utilities/template_measure/resources/BTAPMeasureHelper.rb, lib/openstudio-standards/weather/modify.rb, test/90_1_prm/test_prm_baseline_bldg_jmarrec.rb, test/archive_results.rb, test/doe_prototype/test_daylighting_ctrl.rb, test/doe_prototype/test_sim_control.rb, test/helpers/ci_test_generator.rb, test/helpers/create_deer_prototype_helper.rb, test/modules/qaqc/test_qaqc.rb
Change `Dir.pwd` to `__dir__`, as `__dir__ is more appropriate for tests, where we want the measure to run where the test is. Also change the relative lookup for the weather file path.
=> Update relative paths
